import React, { useEffect, useState, useContext } from "react";
import { useParams } from "react-router-dom";
import { getArtworkDetails } from "../backend/data";
import { motion } from "framer-motion";
import ArtworkDetailBtn from "../components/artwork-detail/ArtworkDetailBtn";
import likeIcon from "../images/love (2).png";
import commentIcon from "../images/comment.png";
import { getGeneratedArtworkDetails } from "../backend/data";
import AuthContext from "../providers/Auth";
import CommentInput from "../components/artwork-detail/CommentInput";
import CounterItem from "../components/artwork-detail/CounterItem";
import AllComments from "../components/artwork-detail/AllComments";
import { collection, query, where, onSnapshot } from "firebase/firestore";
import db from "../backend/firebaseConfig";

const ArtworkDetail = ({ isGeneratedArtwork = false }) => {
  const { id, generatedImageUrl } = useParams();
  const { currentUser } = useContext(AuthContext);
  const [currentArtwork, setCurrentArtwork] = useState(null);
  const [likesCount, setLikesCount] = useState(0);
  const [commentsCount, setCommentsCount] = useState(0);
  const [allComments, setAllComments] = useState([]);

  useEffect(() => {
    // if it's not generated artwork then get it's data by it's id
    if (!isGeneratedArtwork) {
      getArtworkDetails(
        id,
        setCurrentArtwork,
        setLikesCount,
        setCommentsCount,
        setAllComments
      );
    } else {
      // if it's generated by the user, get it's data by it's decoded URL
      getGeneratedArtworkDetails(
        currentUser,
        setCurrentArtwork,
        decodeURIComponent(generatedImageUrl)
      );
    }
  }, [id, generatedImageUrl,allComments]);

  return (
    <>
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.5 }}
        className="artwork-detail"
      >
        <>
          {currentArtwork && (
            <>
              <motion.img
                src={
                  id ? currentArtwork.image : currentArtwork.generatedImageUrl
                }
                alt=""
                className="artwork-detail-img"
                style={{ width: "60%" }}
              />
              <motion.div className="artwork-info">
                <motion.h1>{currentArtwork.model}</motion.h1>
                <motion.h3>{currentArtwork.prompt}</motion.h3>
                <motion.p>{`Prompt was created by ${`Aya`}`}</motion.p>
                <br />
                <div className="artwork-detail-btns">
                  <ArtworkDetailBtn
                    text="Like"
                    artId={id}
                    id="like-btn"
                    setLikesCount={setLikesCount}
                  />
                  <ArtworkDetailBtn text="Save" artId={id} id="save-btn" />
                </div>
                <div className="likes-comments-count">
                  <CounterItem
                    counterIcon={likeIcon}
                    countesNumber={likesCount}
                  />
                  <CounterItem
                    counterIcon={commentIcon}
                    countesNumber={commentsCount}
                  />
                </div>

                <CommentInput artId={id} />
                <AllComments comments={allComments} />

              </motion.div>
            </>
          )}
        </>
      </motion.div>
    </>
  );
};

export default ArtworkDetail;
